//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.28 at 10:51:07 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.morcinek.android.codegenerator.serialization;
